### PR TITLE
Fix insert_at_position in race condition

### LINKED ISSUE #76: Duplicate positions and lost items
We're using acts_as_list in an Ajax UI to allow users to re-order items in a list by dragging and dropping items.

If the user drags and drops a few items in quick succession, this can lead to items being lost and duplicated in the list, e.g. "Item A, Item B, Item C" becomes "Item A, Item C, Item C".

It seems the gem doesn't cope well with overlapping operations, and there is no locking. There doesn't seem to be any behaviour to protect against two items having the same position value.

I have some ideas about how to approach this problem but I wanted to get some guidance first.

Any thoughts?

### PR DESCRIPTION
**Pull request by danielross**
Idea of this PR is to fix #76

### CODE REVIEW

**Comment by danielross** [comment]
Hi @brendon 

I've added a test which simulates the race condition. The idea is to do a bunch of `insert_at` with 4 threads and hope the issue happens (It seems to fail consistently for `n = 1000`).

There is probably a better way of doing it. However I am not very familiar with `minitest` and `sqlite`.
I typically would do this kind of thing using [fork_break](https://github.com/forkbreak/fork_break) and a `postgresql` database

**Comment by brendon** [comment]
Thanks @danielross, that's an interesting approach :) Would something like this work also: http://blog.arkency.com/2015/09/testing-race-conditions/ and be more predictable?

**Comment by danielross** [comment]
That approach is similar to what I'm doing but our problem is slightly different as we need to switch context in the middle of an `insert_position_at` to reveal the bug

**Comment by brendon** [comment]
Overall this looks good. I assume it's best to use locking sparingly, are locking at the last possible opportunity? Looking at the code I think that's probably the case.

@swanandp and @fabn do you have an input on this? I'm trying to think if it could cause unintended problems elsewhere. And should we be locking in other areas also?

File: test/test_list.rb [hunk 1]
```diff
@@ -1,7 +1,10 @@
 # NOTE: following now done in helper.rb (better Readability)
 require 'helper'
 
-ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
+ActiveRecord::Base.establish_connection(
+  adapter: "sqlite3",
+  database: 'file:memdb1?mode=memory&cache=shared'
```
Comment (swanandp) [inline test/test_list.rb]: I have been out of touch with SQLite. What is this line, and why has it changed?

File: test/test_list.rb [hunk 2]
```diff
@@ -161,6 +164,37 @@ def setup
...
+          end
+        end
+      end
+    end
+    wait_for_it = false
+    threads.each(&:join)
+
+    assert_equal (1..n).to_a, ListMixin.where(parent_id: 1).order('pos').map(&:pos)
+  end
 end
```
Comment (swanandp) [inline test/test_list.rb]: 👍 Very cool

**Comment by swanandp** [comment]
Barring that one change about SQLite, this looks good.

File: test/test_list.rb (hunk 1 above)
Comment (danielross) [inline test/test_list.rb]: It is so the sqlite3 database can be shared amongst threads.
https://www.sqlite.org/inmemorydb.html

**Comment by danielross** [comment]
Hi @swanandp what do you reckon regarding the reason I gave for the SQLite change?

File: test/test_list.rb (hunk 1 above)
Comment (swanandp) [inline test/test_list.rb]: I guess this is nice to have, but outside the scope of this PR. Does anything in this PR break w/o that change?

Comment (danielross) [inline test/test_list.rb]: Yes ok. No it doesn't. I have removed it from this PR.

Comment (brendon) [inline test/test_list.rb]: Oh ok, so this change isn't required to support the race condition test?

Comment (danielross) [inline test/test_list.rb]: Sorry I got mixed up when running the tests without the SQLite change and seeing no error but that is because it could not indeed test the race condition...
So this change __is__ required to test the race condition but won't break because only 1 thread will be able to access the database

Comment (brendon) [inline test/test_list.rb]: I think you need an additional test that fails unless you have the SQLite setup correct?

**Comment by brendon** [comment]
@danielross, would you be able to reinstate the necessary connection string to make the test work, then add a test to make sure that if that connection string is removed, then a failure will happen? Once that's done, I think we can merge this :)

**Comment by brendon** [comment]
@danielross are you still keen to get this merged?

**Comment by danielross** [comment]
Hi @brendon. Sorry Yes still keen for this to be merged. I have added back the SQLite setup for multiple thread access.
`test_insert_race_condition` will now fail without the change of adding [with_lock](https://github.com/danielross/acts_as_list/blob/a070fad6bf808e89cb86ec69ea227ec03a3a30fe/lib/acts_as_list/active_record/acts/list.rb#L413)

**Comment by brendon** [comment]
Thanks @danielross, we should probably have an extra test case that fails if the shared database mode isn't set (which caused you confusion before). I fear someone down the road might remove it and not get a failure otherwise. Perhaps there's a way to read the database connection setup and test that it matches a set string?

I guess also add `with_lock` into this PR to fix the problem. Do we need to think about locking all affected records during this update (e.g. the records being updated by the `update_all` queries?). I don't think there's a Rails way for this, and also not sure it's necessary.

**Comment by danielross** [comment]
@brendon I have just added a test for this.
I don't think it is necessary to lock all the records during an update at this stage.

**Comment by brendon** [comment]
Thanks bro. Yea that makes sense. Can you rebase this to remove the conflicts? @swanadp are you happy with this change?

**Comment by danielross** [comment]
I have removed the conflicts with the `master` branch

**Comment by brendon** [comment]
Thanks @danielross :) All merged now.

**Comment by swanandp** [comment]
Nice! Great job @danielross and @brendon !

**Comment by danielross** [comment]
Thanks @brendon and @swanandp :)
