### PR TITLE
Fix deprecation introduced in ActiveRecord 5.1.0.beta1. Closes #257

### LINKED ISSUE #257: Rails 5.1.0.beta1 deprecation
Rails 5.1 deprecates ActiveRecord's `changes` and other related methods (e.g. `attribute_changed?`). See: https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81 and https://github.com/rails/rails/commit/ef993d36bc952046f312a3695617eaa6d5fe352e

Here's one of the warnings:
```
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead.
```

Deprecated use in this gem is here:
https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/list.rb#L396

It's the only one that popped up in my app, but there may be some other deprecated methods in use here.

What's the strategy for handling such deprecations?
`respond_to?("#{position_column}_before_last_save") … else …`?

### PR DESCRIPTION
**Pull request by CvX**
Added ruby 2.4 and Rails 5.1.0.beta1 to test matrix. All tests are passing. Also, the change was tested in a live application.

Thanks to @brendon for guidance! 😃

### CODE REVIEW

File: lib/acts_as_list/active_record/acts/list.rb [hunk 1]
```diff
@@ -393,7 +393,13 @@ def insert_at_position(position)
         end
 
         def update_positions
-          old_position = send("#{position_column}_was") || bottom_position_in_list + 1
+          if ActiveRecord::VERSION::MAJOR >= 5 && ActiveRecord::VERSION::MINOR >= 1
```
Comment (swanandp) [inline lib/acts_as_list/active_record/acts/list.rb]: This should be encapsulated in a method.

File: lib/acts_as_list/active_record/acts/list.rb [hunk 2]
```diff
@@ -393,7 +393,13 @@ def insert_at_position(position)
...
+            old_position = send("#{position_column}_before_last_save")
+          else
+            old_position = send("#{position_column}_was")
```
Comment (swanandp) [inline lib/acts_as_list/active_record/acts/list.rb]: `old_position =` can be outside the `if` clause for better readability.

File: lib/acts_as_list/active_record/acts/list.rb (hunk 1 above)
Comment (CvX) [inline lib/acts_as_list/active_record/acts/list.rb]: ActiveRecord version check? Something along those lines?

```ruby
def activerecord_version_at_least?(major, minor = nil)
  ActiveRecord::VERSION::MAJOR >= major && (!minor || ActiveRecord::VERSION::MINOR >= minor)
end

# activerecord_version_at_least?(5, 1)
```

Or is that way of specifying the version a bit awkward and it would be better to go with version strings?

```ruby
def activerecord_version_at_least?(required)
  Gem::Version.new(ActiveRecord::VERSION::STRING) >= Gem::Version.new(required)
end

# activerecord_version_at_least?('5.1')
```

Comment (swanandp) [inline lib/acts_as_list/active_record/acts/list.rb]: In fact, let's get rid of checking the version altogether, and rely on `respond_to?` for this.  Why check version, When we can duck type.

Comment (CvX) [inline lib/acts_as_list/active_record/acts/list.rb]: I can do either way, but @brendon made a (valid) suggestion that version comparison makes it easier to remove old code path in the future.

That's what's currently done in:
https://github.com/swanandp/acts_as_list/blob/f9b40e1cbdefe5244b787c66da74148e351af26c/lib/acts_as_list/active_record/acts/sequential_updates_method_definer.rb#L8
(which could be replaced w/ eventual `activerecord_version_at_least?('5')`).

Comment (swanandp) [inline lib/acts_as_list/active_record/acts/list.rb]: Makes sense. Let's just leave it at a direct comparison for now, and we can come back to it later.  So no change needed here, just the other minor one and this is good to go.

File: lib/acts_as_list/active_record/acts/list.rb (hunk 2 above)
Comment (CvX) [inline lib/acts_as_list/active_record/acts/list.rb]: Extracted that block to a method. It's clean and leaves original method basically intact.

**Comment by brendon** [comment]
Looks good @CvX :) @swanandp, are you happy for me to merge this? (or you can if you want to) :)

File: lib/acts_as_list/active_record/acts/list.rb (hunk 2 above)
Comment (swanandp) [inline lib/acts_as_list/active_record/acts/list.rb]: Yup, this looks good.

**Comment by swanandp** [comment]
Merged. Thanks @CvX !

**Comment by CvX** [comment]
Hi, have to dig up this PR because I've noticed that the code I committed and which ended up in the repository is incorrect.
Version conditional used here: https://github.com/swanandp/acts_as_list/pull/259/files#diff-708784f0c89e5cdbdd54e18d2b2243d1R406 is wrong for future AR versions: 6.0, 7.0, etc.

We can either correct the conditional (`ActiveRecord::VERSION::MAJOR > 5 || (ActiveRecord::VERSION::MAJOR == 5 && ActiveRecord::VERSION::MINOR >= 1)`) or we could use `Gem::Version` as mentioned before (like this  https://github.com/CvX/acts_as_list/commit/0e7f24f29df8003f42ddb29971c04e5a8b7081be)

Please let me know which way do you prefer and I'll submit a PR.
Sorry for the inconvenience.

**Comment by brendon** [comment]
Thanks @CvX, I've pushed a fix for that to master :) Thanks for picking it up! :)
